import { SineJob } from '../types/sine';

export const INITIAL_SINE_JOBS: SineJob[] = [
  {
    id: 'sine-ter-01',
    titulo: 'Auxiliar Administrativo',
    quantidade: 'Não informado pelo SINE-PI',
    cidade: 'Teresina',
    estado: 'PI',
    escolaridade: 'Não informado pelo SINE-PI',
    experiencia: 'Não informado pelo SINE-PI',
    salario: 'Não informado pelo SINE-PI',
    tipo_contrato: 'CLT',
    modalidade: 'Presencial',
    requisitos: ['Não informado pelo SINE-PI'],
    cnh: 'Não informado pelo SINE-PI',
    beneficios: ['Não informado pelo SINE-PI'],
    observacoes: 'Publicação oficial do SINE-PI. Consulte os requisitos no portal oficial.',
    pcd: false,
    data_publicacao: '18/09/2026',
    data_atualizacao: '18/09/2026',
    data_importacao: Date.now(),
    fonte: 'SINE-PI',
    url_fonte: 'https://portal.pi.gov.br/sine/vagas-de-emprego/',
    hash_vaga: 'hash_aux_admin_ter_01',
    status: 'ATIVA',
    ultima_verificacao: '18/09/2026 às 14:00',
    isNew: true
  },
  {
    id: 'sine-ter-02',
    titulo: 'Atendedor de Balcão',
    quantidade: 'Não informado pelo SINE-PI',
    cidade: 'Teresina',
    estado: 'PI',
    escolaridade: 'Não informado pelo SINE-PI',
    experiencia: 'Não informado pelo SINE-PI',
    salario: 'Não informado pelo SINE-PI',
    tipo_contrato: 'CLT',
    modalidade: 'Presencial',
    requisitos: ['Não informado pelo SINE-PI'],
    cnh: 'Não informado pelo SINE-PI',
    beneficios: ['Não informado pelo SINE-PI'],
    observacoes: 'Vaga exclusiva para Pessoa com Deficiência (PCD).',
    pcd: true,
    data_publicacao: '18/09/2026',
    data_atualizacao: '18/09/2026',
    data_importacao: Date.now(),
    fonte: 'SINE-PI',
    url_fonte: 'https://portal.pi.gov.br/sine/vagas-de-emprego/',
    hash_vaga: 'hash_atendedor_pcd_02',
    status: 'ATIVA',
    ultima_verificacao: '18/09/2026 às 14:00',
    isNew: true
  },
  {
    id: 'sine-ter-03',
    titulo: 'Vendedor Comerciário',
    quantidade: 'Não informado pelo SINE-PI',
    cidade: 'Teresina',
    estado: 'PI',
    escolaridade: 'Não informado pelo SINE-PI',
    experiencia: 'Não informado pelo SINE-PI',
    salario: 'Não informado pelo SINE-PI',
    tipo_contrato: 'CLT',
    modalidade: 'Presencial',
    requisitos: ['Não informado pelo SINE-PI'],
    cnh: 'Não informado pelo SINE-PI',
    beneficios: ['Não informado pelo SINE-PI'],
    observacoes: 'Oportunidade para atuação no comércio lojista de Teresina.',
    pcd: false,
    data_publicacao: '17/09/2026',
    data_atualizacao: '17/09/2026',
    data_importacao: Date.now() - 86400000,
    fonte: 'SINE-PI',
    url_fonte: 'https://portal.pi.gov.br/sine/vagas-de-emprego/',
    hash_vaga: 'hash_vendedor_comercio_03',
    status: 'ATIVA',
    ultima_verificacao: '18/09/2026 às 14:00',
    isNew: false
  }
];
